"""initial

Revision ID: 56de75749916
Revises:
Create Date: 2025-04-10 14:18:50.483976

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56de75749916'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'events',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('client_ip', sa.String(), nullable=False),
        sa.Column('client_user_agent', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('READ', 'CREATE', 'DELETE', name='eventtype'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('secret_id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
    )
    op.create_table(
        'secrets',
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('secret', sa.LargeBinary(), nullable=False),
        sa.Column('passphrase', postgresql.BYTEA(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expired_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    op.drop_table('events')
    # ### end Alembic commands ###
